//
//  TestData.swift
//  NewsDiploma
//
//  Created by Alena  on 12.03.25.
//

import SwiftUI

final class TestData {
    static let modelArray = [
                ArticleModel(
                    articleId: "123",
                    title: "title: Homo antecessor had “a very modern-like face, very similar to the face we our species.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 1"],
                    videoUrl: nil,
                    description: "description: Homo sapiens, have, which is vertical and flat. However, this new hominin is different,” she said.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест1"]
                ),
                ArticleModel(
                    articleId: "567",
                    title: "title: Archaeologists uncovered a cache of 1.5 million-year-old bone tools.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 2"],
                    videoUrl: nil,
                    description: "description: They’re trying to determine who made them",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест2"]
                ),
                ArticleModel(
                    articleId: "891",
                    title: "title: The team also recovered animal bones with cut marks and stone tools used to butcher carcasses from the site.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 2"],
                    videoUrl: nil,
                    description: "description: The population would have inhabited a woodland environment with wet grasslands, which would have been rich in prey, the study said.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест3"]
                ),
                ArticleModel(
                    articleId: "111",
                    title: "title: However, with only small parts of the face, it was impossible to identify the species of hominin conclusively.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 4"],
                    videoUrl: nil,
                    description: "description: As such, the team has assigned it to Homo affinis erectus, with affinis meaning akin to, to indicate that the fossil is closely related to, but distinct from, a known species.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест4"]
                ),
                ArticleModel(
                    articleId: "333",
                    title: "title: However, it wasn’t immediately obvious which species of prehistoric human the team had found, and the study describing the fossils.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 5"],
                    videoUrl: nil,
                    description: "description: Published Wednesday in the journal Nature, doesn’t put forward a definitive answer",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест5"]
                ),
                ArticleModel(
                    articleId: "343",
                    title: "title: Found at the Sima del Elefante site in the Atapuerca Mountains, the fossils make up a partial skull comprised of the left side of the face of an adult hominin.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 5"],
                    videoUrl: nil,
                    description: "description: Fossilized bone fragments unearthed in a cave in northern Spain in 2022 have revealed a previously unknown human population that lived more than 1.1 million years ago, according to new research.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест5"]
                ),
                ArticleModel(
                    articleId: "123",
                    title: "title: Homo antecessor had “a very modern-like face, very similar to the face we our species.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 1"],
                    videoUrl: nil,
                    description: "description: Homo sapiens, have, which is vertical and flat. However, this new hominin is different,” she said.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест1"]
                ),
                ArticleModel(
                    articleId: "567",
                    title: "title: Archaeologists uncovered a cache of 1.5 million-year-old bone tools.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 2"],
                    videoUrl: nil,
                    description: "description: They’re trying to determine who made them",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест2"]
                ),
                ArticleModel(
                    articleId: "891",
                    title: "title: The team also recovered animal bones with cut marks and stone tools used to butcher carcasses from the site.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 2"],
                    videoUrl: nil,
                    description: "description: The population would have inhabited a woodland environment with wet grasslands, which would have been rich in prey, the study said.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест3"]
                ),
                ArticleModel(
                    articleId: "111",
                    title: "title: However, with only small parts of the face, it was impossible to identify the species of hominin conclusively.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 4"],
                    videoUrl: nil,
                    description: "description: As such, the team has assigned it to Homo affinis erectus, with affinis meaning akin to, to indicate that the fossil is closely related to, but distinct from, a known species.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест4"]
                ),
                ArticleModel(
                    articleId: "333",
                    title: "title: However, it wasn’t immediately obvious which species of prehistoric human the team had found, and the study describing the fossils.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 5"],
                    videoUrl: nil,
                    description: "description: Published Wednesday in the journal Nature, doesn’t put forward a definitive answer",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест5"]
                ),
                ArticleModel(
                    articleId: "343",
                    title: "title: Found at the Sima del Elefante site in the Atapuerca Mountains, the fossils make up a partial skull comprised of the left side of the face of an adult hominin.",
                    link: "https://example.com",
                    keywords: ["тест"],
                    creator: ["Автор 5"],
                    videoUrl: nil,
                    description: "description: Fossilized bone fragments unearthed in a cave in northern Spain in 2022 have revealed a previously unknown human population that lived more than 1.1 million years ago, according to new research.",
                    content: "Содержимое примера.",
                    pubDate: Date(),
                    pubDateTZ: "GMT+3",
                    imageUrl: nil,
                    sourceId: "1",
                    sourcePriority: 1,
                    sourceName: "Источник",
                    sourceUrl: "https://example.com",
                    sourceIcon: "",
                    language: "ru",
                    country: ["BY"],
                    category: ["Тест5"]
                )
            ]
    
    static let articleModel = ArticleModel(
        articleId: "343",
        title: "Found at the Sima del Elefante site in the Atapuerca Mountains, the fossils make up a partial skull comprised of the left side of the face of an adult hominin.",
        link: "https://example.com",
        keywords: ["тест"],
        creator: ["Автор 5"],
        videoUrl: nil,
        description: "Fossilized bone fragments unearthed in a cave in northern Spain in 2022 have revealed a previously unknown human population that lived more than 1.1 million years ago, according to new research.",
        content: "Содержимое примера.",
        pubDate: Date(),
        pubDateTZ: "GMT+3",
        imageUrl: nil,
        sourceId: "1",
        sourcePriority: 1,
        sourceName: "Источник",
        sourceUrl: "https://example.com",
        sourceIcon: "",
        language: "ru",
        country: ["BY"],
        category: ["Тест5"]
    )
}


